server:
  port: 9999


spring:
  datasource:
    url:  jdbc:mysql://124.220.22.22:3306/messageboard?allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 521666
mybatis:
  mapper-locations: classpath:/mappers/*.xml


